name: Takeshi
version: '${project.version}'
main: de.silvan.takeshi.Takeshi
api-version: '1.20'

commands:
  warp:
  w:
  welt:
  world:
  lobby:
  l:
  hub:
  watch:
  startflappybird:
  start:
  joingame: